# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: yarn install -g
    - run: npm install -g   
    - run: npm install --package-lock
    - run: npm ci
    - run: yarn run build
    - run: yarn add gh-pages 
    - run: yarn next export
    - run: touch ./out/.nojekyll
    - run: yarn start
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.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 }}
        BRANCH: gh-pages
        FOLDER: out
