name: Node.js CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: yarn install -g --frozen-lockfile
    - run: npm install -g   
    - run: npm install --package-lock
    - run: npm ci
    - run: yarn run build
    - run: yarn add gh-pages 
    - run: yarn next export
    - run: touch ./out/.nojekyll
    - run: yarn start
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.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 }}
        BRANCH: gh-pages
        FOLDER: out
